services:
  - type: web
    name: snake-arena-app
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-area-db
          property: connectionString
      - key: PORT
        value: 8000

databases:
  - name: snake-area-db
    databaseName: snake_arena
    user: snakeuser
    plan: free
    region: oregon
